import { ArrowLeft, Video } from "lucide-react";
import Image from "next/image";
import { notFound } from "next/navigation";
import { getFormatter, getTranslations } from "next-intl/server";

import { requireProjectAccess } from "@/Lib/projects/auth";
import { createProjectJournalMediaDeliveries } from "@/Lib/projects/mediaDelivery";
import { getAccessibleProject, listProjectDayTrackEvidence } from "@/Lib/projects/queries";
import { buildProjectExpeditionReport } from "@/Lib/projects/report";
import { deriveProjectTrackVerification } from "@/Lib/projects/tracks";
import ProjectReportPrintButton from "@/components/projects/ProjectReportPrintButton";
import type { Locale } from "@/i18n/locales";
import { Link } from "@/i18n/navigation";

export default async function ProjectReportPage({ params }: { params: Promise<{ locale: Locale; projectId: string }> }) {
  const { locale, projectId } = await params;
  const { supabase, user } = await requireProjectAccess(locale, `/projects/${projectId}/report`, projectId);
  const [t, format, project] = await Promise.all([getTranslations({ locale, namespace: "Projects.Report" }), getFormatter({ locale }), getAccessibleProject(supabase, projectId)]);
  if (!project) notFound();
  const evidence = await listProjectDayTrackEvidence(supabase, user.id, project.id);
  for (const day of project.days) day.trackEvidence = evidence.filter((track) => track.projectDayId === day.id);
  const report = buildProjectExpeditionReport(project);
  const deliveries = await createProjectJournalMediaDeliveries(supabase, project.journalEntries.flatMap((entry) => entry.media));
  const deliveryById = new Map(deliveries.map((item) => [item.id, item]));
  const duration = (seconds: number | null) => seconds === null ? t("statisticsUnavailable") : `${Math.floor(seconds / 3600)}:${String(Math.floor((seconds % 3600) / 60)).padStart(2, "0")} h`;
  return <main className="project-report min-h-screen bg-[var(--color-bg)] px-4 py-6 print:bg-white print:p-0"><article className="mx-auto max-w-5xl bg-[var(--color-surface)] p-5 shadow-[var(--shadow-card)] print:max-w-none print:p-0 print:shadow-none sm:p-8">
    <nav className="project-report-control flex flex-wrap justify-between gap-3"><Link href={`/projects/${project.id}`} className="ui-pressable inline-flex min-h-11 items-center gap-2 font-bold"><ArrowLeft aria-hidden="true" size={17}/>{t("backToProject")}</Link><ProjectReportPrintButton label={t("printReport")}/></nav>
    <header className="mt-6 border-b-2 border-[var(--color-text)] pb-6 print:mt-0"><p className="text-xs font-bold uppercase tracking-[0.12em]">Mountain Tracker · {t("privateReport")}</p><h1 className="mt-3 break-words text-4xl font-bold">{project.name}</h1><p className="mt-2 text-sm text-[var(--color-text-muted)]">{t(report.reportState === "completed" ? "expeditionReport" : "expeditionReportPreview")} · {project.status}</p></header>
    <section className="mt-6" aria-labelledby="report-summary"><h2 id="report-summary" className="text-2xl font-bold">{t("reportSummary")}</h2><dl className="mt-4 grid grid-cols-2 gap-4 sm:grid-cols-3 lg:grid-cols-4">{[[t("daysWithEvidence"),`${report.summary.daysWithGpsEvidence}/${report.summary.totalDays}`],[t("uniqueTracks"),report.summary.uniqueTrackCount],[t("totalDistance"),`${format.number(report.summary.totalDistanceM/1000,{maximumFractionDigits:1})} km`],[t("totalElevationGain"),`${format.number(report.summary.totalElevationGainM)} m`],[t("totalDuration"),duration(report.summary.totalDurationSeconds)],[t("verifiedMountains"),report.summary.verifiedMountainCount],[t("photos"),report.summary.photoCount],[t("videos"),report.summary.videoCount]].map(([label,value])=><div key={String(label)}><dt className="text-xs text-[var(--color-text-muted)]">{label}</dt><dd className="mt-1 text-xl font-bold">{value}</dd></div>)}</dl></section>
    <section className="mt-8" aria-labelledby="mountain-outcomes"><h2 id="mountain-outcomes" className="text-2xl font-bold">{t("mountainOutcomes")}</h2><ul className="mt-3 grid gap-2 sm:grid-cols-2">{project.mountains.map((mountain)=>{const outcome=report.summary.mountainEvidence.find((item)=>item.mountainId===mountain.id)?.state??"no-evidence";return <li key={mountain.id} className="report-card flex justify-between gap-3 border p-3"><span className="font-bold">{mountain.nameDe??mountain.name??`#${mountain.id}`}</span><span>{t(outcome)}</span></li>;})}</ul></section>
    <section className="mt-8" aria-labelledby="day-timeline"><h2 id="day-timeline" className="text-2xl font-bold">{t("dayTimeline")}</h2><div className="mt-4 space-y-8">{report.days.map(({day,journalEntries})=>{const media=journalEntries.flatMap((entry)=>entry.media);return <section key={day.id} className="report-day border-t-2 pt-4"><h3 className="text-xl font-bold">{t("day",{number:day.dayNumber})}{day.date?` · ${format.dateTime(new Date(`${day.date}T00:00:00Z`),{dateStyle:"long",timeZone:"UTC"})}`:""}</h3><div className="mt-4 grid gap-6 md:grid-cols-2"><div><h4 className="font-bold uppercase tracking-wide">{t("planned")}</h4><p className="mt-2 text-sm">{day.mountains.map((m)=>m.nameDe??m.name??`#${m.id}`).join(" · ")||t("noEvidence")}</p>{day.notes&&<p className="mt-2 whitespace-pre-wrap text-sm">{day.notes}</p>}</div><div><h4 className="font-bold uppercase tracking-wide">{t("actual")}</h4>{day.trackEvidence.length===0?<p className="mt-2 text-sm text-[var(--color-text-muted)]">{t("noEvidence")}</p>:<ul className="mt-2 space-y-2">{day.trackEvidence.map((track)=><li key={track.relationId} className="report-card border p-3 text-sm"><p className="font-bold">{track.title??`#${track.activityId}`} · {t(deriveProjectTrackVerification(track))}</p><p className="mt-1">{track.distanceM===null?t("statisticsUnavailable"):`${format.number(track.distanceM/1000,{maximumFractionDigits:1})} km`} · {duration(track.durationSeconds)} · {track.elevationGainM===null?t("statisticsUnavailable"):`+${format.number(track.elevationGainM)} m`}</p></li>)}</ul>}</div></div>{journalEntries.filter((entry)=>entry.body.trim()||entry.title).length>0&&<div className="mt-5"><h4 className="font-bold">{t("journal")}</h4>{journalEntries.filter((entry)=>entry.body.trim()||entry.title).map((entry)=><article key={entry.id} className="report-card mt-2 border-l-2 pl-3"><p className="text-xs text-[var(--color-text-muted)]">{format.dateTime(new Date(entry.entryDate),{dateStyle:"medium"})}</p>{entry.title&&<h5 className="font-bold">{entry.title}</h5>}{entry.body.trim()&&<p className="whitespace-pre-wrap text-sm">{entry.body}</p>}</article>)}</div>}{media.length>0&&<div className="report-media-grid mt-5 grid grid-cols-3 gap-2 sm:grid-cols-5">{media.map((item)=>{const delivery=deliveryById.get(item.id);return <figure key={item.id} className="report-media relative aspect-[4/3] overflow-hidden border bg-[var(--color-surface-muted)]">{item.mediaType==="photo"&&delivery?.signedUrl?<Image unoptimized fill sizes="(max-width: 639px) 33vw, 20vw" src={delivery.signedUrl} alt={item.originalFilename} className="object-contain"/>:<div className="flex h-full flex-col items-center justify-center p-2 text-center text-xs"><Video aria-hidden="true" size={22}/><span>{item.mediaType==="video"?t("video"):t("mediaUnavailable")}</span>{item.durationSeconds!==null&&<span>{duration(item.durationSeconds)}</span>}</div>}</figure>;})}</div>}</section>;})}</div></section>
    <footer className="mt-10 border-t pt-4 text-xs text-[var(--color-text-muted)]">{t("generatedFromProject")}</footer>
  </article></main>;
}
