import "server-only";
import type { SupabaseClient } from "@supabase/supabase-js";
export const PUBLIC_EXPEDITION_PAGE_SIZE=20;
export const PUBLIC_EXPEDITION_SORTS=["recent","distance","elevation","duration"] as const;
export type PublicExpeditionSort=typeof PUBLIC_EXPEDITION_SORTS[number];
export type PublicExpeditionCard={slug:string;name:string;status:"completed"|"archived";startDate:string|null;endDate:string|null;dayCount:number;mountainNames:string[];verifiedMountainCount:number;daysWithGpsEvidence:number;uniqueTrackCount:number;totalDistanceM:number;totalElevationGainM:number;totalDurationSeconds:number;sortValue:number};
export type PublicExpeditionSearch={q:string;year:number|null;minDistanceKm:number|null;maxDistanceKm:number|null;evidence:boolean;status:"completed"|"archived"|null;sort:PublicExpeditionSort;cursorValue:number|null;cursorSlug:string|null};
const numeric=(v:unknown)=>Number.isFinite(Number(v))?Number(v):0;
export function parsePublicExpeditionSearch(input:Record<string,string|string[]|undefined>):PublicExpeditionSearch{const one=(key:string)=>typeof input[key]==="string"?input[key] as string:"";const bounded=(key:string,min:number,max:number)=>{const value=Number(one(key));return Number.isFinite(value)&&value>=min&&value<=max?value:null};const sort=one("sort"),status=one("status");return{q:one("q").trim().slice(0,80),year:bounded("year",1900,2200),minDistanceKm:bounded("minDistance",0,10000),maxDistanceKm:bounded("maxDistance",0,10000),evidence:one("evidence")==="1",status:status==="completed"||status==="archived"?status:null,sort:PUBLIC_EXPEDITION_SORTS.includes(sort as PublicExpeditionSort)?sort as PublicExpeditionSort:"recent",cursorValue:bounded("cursor",0,9999999999999),cursorSlug:/^[A-Za-z0-9_-]{32,128}$/.test(one("after"))?one("after"):null};}
export async function searchPublicExpeditions(supabase:SupabaseClient,search:PublicExpeditionSearch):Promise<{cards:PublicExpeditionCard[];next:{value:number;slug:string}|null}>{const{data,error}=await supabase.rpc("search_public_expeditions",{search_text:search.q||null,filter_year:search.year,minimum_distance_m:search.minDistanceKm===null?null:Math.round(search.minDistanceKm*1000),maximum_distance_m:search.maxDistanceKm===null?null:Math.round(search.maxDistanceKm*1000),required_evidence:search.evidence,filter_status:search.status,sort_mode:search.sort,cursor_value:search.cursorValue,cursor_slug:search.cursorSlug,result_limit:PUBLIC_EXPEDITION_PAGE_SIZE+1});if(error)throw error;const rows=(data??[]) as Record<string,unknown>[];const cards=rows.slice(0,PUBLIC_EXPEDITION_PAGE_SIZE).flatMap((r):PublicExpeditionCard[]=>typeof r.public_slug==="string"&&typeof r.name==="string"&&(r.status==="completed"||r.status==="archived")?[{slug:r.public_slug,name:r.name,status:r.status,startDate:typeof r.start_date==="string"?r.start_date:null,endDate:typeof r.end_date==="string"?r.end_date:null,dayCount:numeric(r.day_count),mountainNames:Array.isArray(r.mountain_names)?r.mountain_names.filter((n):n is string=>typeof n==="string"):[],verifiedMountainCount:numeric(r.verified_mountain_count),daysWithGpsEvidence:numeric(r.days_with_gps_evidence),uniqueTrackCount:numeric(r.unique_track_count),totalDistanceM:numeric(r.total_distance_m),totalElevationGainM:numeric(r.total_elevation_gain_m),totalDurationSeconds:numeric(r.total_duration_seconds),sortValue:numeric(r.sort_value)}]:[]);const last=cards.at(-1);return{cards,next:rows.length>PUBLIC_EXPEDITION_PAGE_SIZE&&last?{value:last.sortValue,slug:last.slug}:null};}
