"use client";

import { useEffect, useRef, useState } from "react";
import { LoaderCircle, Plus, UserRound, Users, X } from "lucide-react";
import { useTranslations } from "next-intl";

import { cancelProjectInvitation, changeProjectMemberRole, inviteProjectMember, removeProjectMember, searchProjectParticipants, type ProjectIdentity, type ProjectMemberRole, type ProjectTeam } from "@/Lib/projects/collaboration";
import { createClient } from "@/Lib/supabase/client";
import { useRouter } from "@/i18n/navigation";

export default function ProjectTeamSection({ projectId, team, canInvite }: { projectId: string; team: ProjectTeam; canInvite: boolean }) {
  const t = useTranslations("Projects.Team"); const router = useRouter();
  const dialog = useRef<HTMLDialogElement>(null); const opener = useRef<HTMLButtonElement>(null);
  const [busy, setBusy] = useState(""); const [message, setMessage] = useState("");
  const [query, setQuery] = useState(""); const [results, setResults] = useState<ProjectIdentity[]>([]); const [selected, setSelected] = useState<ProjectIdentity | null>(null); const [role, setRole] = useState<ProjectMemberRole>("editor");
  useEffect(() => { if (query.trim().length < 2) return; const timer = window.setTimeout(() => { void searchProjectParticipants(createClient(), query).then(setResults).catch(() => setMessage(t("invitationFailed"))); }, 250); return () => window.clearTimeout(timer); }, [query, t]);
  function close() { dialog.current?.close(); opener.current?.focus(); setSelected(null); setQuery(""); setResults([]); }
  async function run(key: string, task: () => Promise<{ ok: boolean }>, success: string) { if (busy) return; setBusy(key); const result = await task(); setBusy(""); setMessage(result.ok ? success : t("invitationFailed")); if (result.ok) router.refresh(); }
  async function send() { if (!selected) return; await run("invite", () => inviteProjectMember(createClient(), projectId, selected.userId, role), t("invitationSent")); close(); }
  const unavailableIds = new Set([team.owner?.userId, ...team.members.map((m) => m.userId), ...team.invitations.map((i) => i.userId)]);
  return <section className="border border-[var(--color-border)] bg-[var(--color-surface)] p-4 shadow-[var(--shadow-control)]" aria-labelledby="expedition-team-title">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><h2 id="expedition-team-title" className="flex items-center gap-2 text-xl font-bold"><Users aria-hidden="true" size={19}/>{t("expeditionTeam")}</h2><p className="mt-1 text-sm text-[var(--color-text-muted)]">{t("description")}</p></div>{canInvite && <button ref={opener} type="button" onClick={() => dialog.current?.showModal()} className="ui-pressable inline-flex min-h-11 items-center gap-2 rounded-[var(--radius-control)] bg-[var(--color-forest)] px-3 font-bold text-white"><Plus aria-hidden="true" size={16}/>{t("inviteParticipant")}</button>}</div>
    <div className="mt-4 space-y-3"><IdentityRow identity={team.owner} role={t("owner")}/>{team.members.length === 0 && <p className="text-sm text-[var(--color-text-muted)]">{t("noMembers")}</p>}{team.members.map((member) => <div key={member.id} className="flex flex-col gap-3 border-t border-[var(--color-border-soft)] pt-3 sm:flex-row sm:items-center"><Identity identity={member}/><div className="flex min-w-0 items-center gap-2 sm:ml-auto"><label className="sr-only" htmlFor={`role-${member.id}`}>{t("changeRole", { name: member.displayName ?? member.username })}</label><select id={`role-${member.id}`} value={member.role} disabled={Boolean(busy)} onChange={(event) => void run(member.id, () => changeProjectMemberRole(createClient(), projectId, member.userId, event.target.value as ProjectMemberRole), t("roleChanged"))} className="min-h-11 rounded-[var(--radius-control)] border border-[var(--color-border)] bg-[var(--color-surface)] px-3"><option value="editor">{t("editor")}</option><option value="viewer">{t("viewer")}</option></select><button type="button" disabled={Boolean(busy)} onClick={() => window.confirm(t("removeMemberConfirm", { name: member.displayName ?? member.username })) && void run(member.id, () => removeProjectMember(createClient(), projectId, member.userId), t("memberRemoved"))} className="ui-pressable min-h-11 px-2 font-bold text-[var(--color-danger)]">{t("removeMember")}</button></div></div>)}</div>
    <h3 className="mt-5 border-t border-[var(--color-border)] pt-4 font-bold">{t("pendingInvitations")}</h3>{team.invitations.length === 0 ? <p className="mt-2 text-sm text-[var(--color-text-muted)]">{t("noPendingInvitations")}</p> : <div className="mt-2 space-y-2">{team.invitations.map((invite) => <div key={invite.id} className="flex flex-col gap-2 sm:flex-row sm:items-center"><Identity identity={invite}/><span className="text-sm text-[var(--color-text-muted)] sm:ml-auto">{t("invitedAs", { role: t(invite.role) })}</span><button type="button" disabled={Boolean(busy)} onClick={() => void run(invite.id, () => cancelProjectInvitation(createClient(), invite.id), t("invitationCancelled"))} className="ui-pressable min-h-11 px-2 font-bold text-[var(--color-danger)]">{t("cancelInvitation")}</button></div>)}</div>}
    <p aria-live="polite" className="mt-3 text-sm text-[var(--color-text-muted)]">{message}</p>
    <dialog ref={dialog} onCancel={(event) => { event.preventDefault(); close(); }} onClose={() => opener.current?.focus()} className="m-auto max-h-[calc(100dvh-2rem)] w-[calc(100%-2rem)] max-w-lg rounded-[var(--radius-card)] bg-[var(--color-surface)] p-0 text-[var(--color-text)] shadow-2xl backdrop:bg-black/55">
      <div className="p-5 sm:p-6"><div className="flex items-start justify-between gap-4"><div><h2 className="text-2xl font-bold">{t("inviteParticipant")}</h2><p className="mt-1 text-sm text-[var(--color-text-muted)]">{t("inviteParticipantDescription")}</p></div><button type="button" onClick={close} aria-label={t("closeDialog")} className="ui-pressable grid min-h-11 min-w-11 place-items-center"><X aria-hidden="true"/></button></div>
      <label htmlFor="participant-search" className="mt-5 block font-bold">{t("selectParticipant")}</label><input id="participant-search" autoFocus value={query} onChange={(e) => { const next = e.target.value; setQuery(next); setSelected(null); if (next.trim().length < 2) setResults([]); }} placeholder={t("searchPlaceholder")} className="mt-2 min-h-11 w-full rounded-[var(--radius-control)] border border-[var(--color-border)] bg-[var(--color-surface)] px-3"/>
      {results.length > 0 && <ul className="mt-2 max-h-48 overflow-y-auto border border-[var(--color-border)]">{results.map((user) => { const unavailable = unavailableIds.has(user.userId); return <li key={user.userId}><button type="button" disabled={unavailable} onClick={() => setSelected(user)} className={`ui-pressable flex min-h-12 w-full items-center px-3 text-left disabled:opacity-45 ${selected?.userId === user.userId ? "bg-[var(--color-forest-soft)]" : ""}`}><Identity identity={user}/>{unavailable && <span className="ml-auto text-xs">{t("alreadyInvited")}</span>}</button></li>; })}</ul>}
      <label htmlFor="participant-role" className="mt-4 block font-bold">{t("selectRole")}</label><select id="participant-role" value={role} onChange={(e) => setRole(e.target.value as ProjectMemberRole)} className="mt-2 min-h-11 w-full rounded-[var(--radius-control)] border border-[var(--color-border)] bg-[var(--color-surface)] px-3"><option value="editor">{t("editor")}</option><option value="viewer">{t("viewer")}</option></select>
      <button type="button" disabled={!selected || Boolean(busy)} onClick={() => void send()} className="ui-pressable mt-5 inline-flex min-h-11 w-full items-center justify-center gap-2 rounded-[var(--radius-control)] bg-[var(--color-forest)] px-4 font-bold text-white disabled:opacity-50">{busy === "invite" && <LoaderCircle aria-hidden="true" className="animate-spin" size={16}/>} {t("sendInvitation")}</button></div>
    </dialog>
  </section>;
}

function IdentityRow({ identity, role }: { identity: ProjectIdentity | null; role: string }) { return identity ? <div className="flex items-center"><Identity identity={identity}/><span className="ml-auto rounded-full bg-[var(--color-surface-muted)] px-3 py-1 text-xs font-bold">{role}</span></div> : null; }
function Identity({ identity }: { identity: ProjectIdentity }) { return <div className="flex min-w-0 flex-1 items-center gap-3"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-[var(--color-forest-soft)] text-[var(--color-forest)]"><UserRound aria-hidden="true" size={18}/></span><span className="min-w-0"><span className="block truncate font-bold">{identity.displayName ?? identity.username}</span><span className="block truncate text-xs text-[var(--color-text-muted)]">@{identity.username}</span></span></div>; }
